'use client'

import React, { createContext, useState, useEffect } from 'react'

export const translations = {
  en: {
    shipping: 'Shipping',
    ship: 'Ship',
    tracking: 'Tracking',
    support: 'Support',
    signIn: 'Sign In',
    register: 'Register',
    signOut: 'Sign Out',
    settings: 'Settings',
    adminPanel: 'Admin Panel',
    dashboard: 'Account Center',
    language: 'Language',
    professionalLogistics: 'Smart Logistics Solutions for Your Business',
    connectWithLeading: 'Empowering your shipments with seamless, efficient, and reliable logistics services worldwide.',
    shipPackages: 'Ship Packages',
    createShipments: 'Create shipments with our partner logistics companies.',
    startShipping: 'Start Shipping',
    trackDeliveries: 'Track Deliveries',
    realTimeTracking: 'Real-time tracking for all your shipments.',
    trackNow: 'Track Now',
    billingPayments: 'Billing & Payments',
    manageInvoices: 'Manage your invoices and payment methods.',
    viewBilling: 'View Billing',
    monthlyBilling: 'Monthly Billing for Verified Merchants',
    monthlyBillingDesc: 'After verification of your business information, enjoy the convenience of monthly billing. All your shipping costs are consolidated into a single monthly invoice for easy management.',
    learnMore: 'Learn More',
    applyForMonthlyBilling: 'Apply for Monthly Billing',
    whyChoose: 'Why Choose KAIFA EXPRESS?',
    fastDelivery: 'Fast Delivery',
    quickReliable: 'Quick and reliable delivery across Europe',
    realTimeTrackingTitle: 'Real-time Tracking',
    trackPackages: 'Track your packages in real-time',
    support247: '24/7 Support',
    roundTheClock: 'Round-the-clock customer support',
    quickActions: 'Quick Actions',
    trackPackage: 'Track Package',
    createShipment: 'Create Shipment',
    viewBillingInfo: 'View Billing',
    printDocuments: 'Print Documents',
    track: 'Track',
    trackYourPackage: 'Track Your Package',
    enterTrackingNumber: 'Enter tracking number',
    trackButton: 'Track',
    recentOrders: 'Recent Orders',
    orderHistory: 'Order History',
    orderDetail: 'Order Detail',
    trackingNumber: 'Tracking Number',
    status: 'Status',
    sender: 'Sender',
    recipient: 'Recipient',
    packageInformation: 'Package Information',
    trackingTimeline: 'Tracking Timeline',
    share: 'Share',
    shareTo: 'Share to',
    viewLogistics: 'View Logistics',
    pendingPickup: 'Pending Pickup',
    inTransit: 'In Transit',
    outForDelivery: 'Package is out for delivery to recipient.',
    delivered: 'Delivered',
    attemptFailed: 'Attempt Failed',
    exception: 'Exception',
    cancelled: 'Cancelled',
    packageType: 'Type',
    weight: 'Weight (kg)',
    length: 'Length (cm)',
    width: 'Width (cm)',
    height: 'Height (cm)',
    description: 'Description',
    serviceType: 'Service Type',
    insurance: 'Insurance',
    needsPallet: 'Needs Pallet',
    palletSize: 'Pallet Size',
    trackingUrl: 'Tracking URL',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    login: 'Login',
    welcomeBack: 'Welcome back',
    loginToYourAccount: 'Login to your account',
    savedAccounts: 'Saved Accounts',
    systemSettings: 'System Settings',
    userManagement: 'User Management',
    systemLogs: 'System Logs',
    orders: 'Orders',
    customers: 'Customers',
    billing: 'Billing',
    reports: 'Reports',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    upload: 'Upload',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    close: 'Close',
    open: 'Open',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    printShare: 'Print/Share',
    printPdf: 'Print PDF',
    shareOrder: 'Share Order',
    shareButtonMessage: 'Please use the share button in Tracking for full functionality.',
    orderDetails: 'Order Details',
    packageCount: 'Package Count',
    recipientInfo: 'Recipient Information',
    senderInfo: 'Sender Information',
    downloadPdf: 'Print',
    downloadConfirm: 'Do you want to print the order details?',
    selectOrderToView: 'Select an order to view details',
    view_all_info: 'View all info',
    orderNumber: 'Order Number',
    packageService: 'Package&Service',
    reviewOrder: 'Order Confirmation',
    addPackage: 'Add Package',
    areYouSureDeletePackage: 'Are you sure you want to delete this package? This action cannot be undone.',
    deleteThisPackage: 'Delete this package',
    placeOrder: 'Place Order',
    selectCountry: 'Select Country',
    saveToAddressBook: 'Save to address book',
    enterKFCode: 'Enter KF Code',
    searchSender: 'Search sender',
    searchRecipient: 'Search recipient',
    document: 'Document',
    fragile: 'Fragile',
    electronics: 'Electronics',
    serviceOptions: 'Service Options',
    standardDelivery: 'Standard Delivery',
    expressDelivery: 'Express Delivery',
    addInsuranceCoverage: 'Add insurance coverage (+€5.99)',
    needPallet: 'Need pallet?',
    pleaseSelectPalletSize: 'Please select pallet size',
    palletSize1: '1. 100cm × 50cm',
    palletSize2: '2. 140cm × 80cm',
    delayedPickup: 'Delayed pickup',
    delayedPickupDescription: 'Our Service supports pickup after 16:00 for same-day orders. To ensure timely shipping, please prepare your package and label in advance. We will contact you.',
    notProvided: 'Not provided',
    kfCode: 'KF Code',
    pallet: 'Pallet',
    monthlyBillingDescription: "Your monthly bill will be sent to your email and can be viewed in the 'Account Center'.",
    orderSubmittedSuccessfully: 'Order submitted successfully!',
    germany: 'Germany',
    france: 'France',
    italy: 'Italy',
    spain: 'Spain',
    netherlands: 'Netherlands',
    belgium: 'Belgium',
    austria: 'Austria',
    switzerland: 'Switzerland',
    fullName: 'Full Name',
    clear: 'Clear',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    package: 'Package',
    service: 'Service',
    review: 'Review',
    trackingNumberShort: 'Tracking No.',
    trackYourShipment: 'Track Your Shipment',
    enterPackageNumberPlaceholder: 'Enter your package number',
    trackingLoading: 'Tracking in progress... Please wait.',
    viewAllInfo: 'View All Info',
    sampleOrderNumber: 'Sample Order Number',
    pleasePasteLinkInWeChat: 'Please paste the link in WeChat to share.',
    wechat: 'WeChat',
    pickedUp: 'Picked Up',
    labelCreated: 'Label Created',
    departedFromFacility: 'Departed from facility',
    packagePickedUpByCarrier: 'Package picked up by carrier',
    shippingLabelCreated: 'Shipping label created',
    frankfurtGermany: 'Frankfurt, Germany',
    berlinGermany: 'Berlin, Germany',
    backToTrack: 'Back to Track',
    shipmentHistory: 'Shipment History',
    filters: 'Filters',
    prev: 'Prev',
    showingShipments: 'Showing',
    of: 'of',
    backToOrderHistory: 'Back to Order History',
    orderPlaced: 'Order Placed',
    orderPlacedDesc: 'Order has been placed and is awaiting processing.',
    readyForPickup: 'Order is ready for pickup by the carrier.',
    inTransitToDestination: 'Package is in transit to destination.',
    packageDeliveredToRecipient: 'Package delivered to recipient.',
    contactCustomerService: 'Contact Customer Service',
    guide: 'Guide',
    howCanWeHelp: 'How can we help you?',
    orderStatusAndTracking: 'Order status and tracking inquiries',
    shippingAndDelivery: 'Shipping and delivery questions',
    accountAndBilling: 'Account and billing support',
    feedbackAndSuggestions: 'Feedback and suggestions',
    userGuide: 'User Guide',
    howToUse: 'How to Use KAIFA EXPRESS',
    registerOrLogin: 'Register or log in to your account',
    fillSenderRecipient: 'Fill in sender and recipient information',
    chooseServiceAndPackage: 'Choose your shipping service and package details',
    submitOrderAndPay: 'Submit your order and make payment',
    trackShipment: 'Track your shipment in real time',
    faq: 'Frequently Asked Questions',
    faqTrackOrder: 'How do I track my order?',
    faqShippingOptions: 'What shipping options are available?',
    faqContactCustomerService: 'How do I contact customer service?',
    faqChangeAddress: 'How do I change my delivery address?',
    statTotalOrders: 'Total Orders',
    statActiveCustomers: 'Active Customers',
    statInTransit: 'In Transit',
    statRevenue: 'Revenue (€)',
    statFromLastMonth: 'from last month',
    topRoutes: 'Top Routes',
    ordersLabel: 'orders',
    revenueLabel: 'Revenue',
    createOrder: 'Create Order',
    addNewShipment: 'Add new shipment',
    addCustomer: 'Add Customer',
    registerNewCustomer: 'Register new customer',
    viewReports: 'View Reports',
    analyticsInsights: 'Analytics & insights',
    kaifaAdmin: 'KAIFA Admin',
    superAdmin: 'Super Admin',
    admin: 'Admin',
    searchPlaceholder: 'Search...',
    paymentManagement: 'Payment Management',
    all: 'All',
    paid: 'Paid',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    customer: 'Customer',
    billNo: 'Bill No.',
    amount: 'Amount',
    dueDate: 'Due Date',
    action: 'Action',
    remindPayment: 'Remind Payment',
    remindAreaTitle: 'Reminders',
    noReminders: 'No reminders yet.',
    backToDashboard: 'Back to Dashboard',
    profile: 'Profile',
    orders: 'Orders',
    totalOrders: 'Total Orders',
    inTransit: 'In Transit',
    delivered: 'Delivered',
    createShipment: 'Create Shipment',
    sendNewPackage: 'Send new package',
    trackPackage: 'Track Package',
    checkDeliveryStatus: 'Check delivery status',
    viewBilling: 'View Billing',
    managePayments: 'Manage payments',
    remind: 'Remind',
    remindSent: 'Your reminder has been sent successfully.',
    viewAllInfo: 'View All Info',
    clearReminders: 'Clear',
    processReminders: 'Process All',
    businessVerificationRequired: 'Business Verification Required',
    businessVerificationDesc: 'To access monthly billing and other premium features, please complete your business verification.',
    monthlyShippingServices: 'Monthly shipping services - {month}',
    expressDeliveryServices: 'Express Delivery Services - {month}',
    standardDeliveryServices: 'Standard Delivery Services - {month}',
    overnightDeliveryServices: 'Overnight Delivery Services - {month}',
    backToHome: 'Back to Home',
    billingAndPayments: 'Billing & Payments',
    verificationStatusPending: 'Pending',
    verificationStatusApproved: 'Approved',
    verificationStatusRejected: 'Rejected',
    addPaymentMethod: 'Add Payment Method',
    setAsDefault: 'Set as Default',
    default: 'Default',
    remove: 'Remove',
    overview: 'Overview',
    invoices: 'Invoices',
    monthlyBills: 'Monthly Bills',
    paymentMethods: 'Payment Methods',
    current: 'Current',
    previous: 'Previous',
    due: 'Due',
    download: 'Download',
    view: 'View',
    details: 'Details',
    shipments: 'Shipments',
    period: 'Period',
    registrationDate: 'Registration Date',
    businessName: 'Business Name',
    eligibleForMonthlyBilling: 'Eligible for Monthly Billing',
    notEligibleForMonthlyBilling: 'Not Eligible for Monthly Billing',
    verification: 'Verification',
    verifyNow: 'Verify Now',
    completeVerification: 'Complete Verification',
    monthlyBillingStatus: 'Monthly Billing Status',
    monthlyBillingActive: 'Monthly billing is active',
    monthlyBillingEligibleDesc: 'Your business is eligible for monthly consolidated billing.',
    monthlyBillingNotAvailable: 'Monthly billing not available',
    monthlyBillingNotAvailableDesc: 'Complete business verification to enable monthly billing.',
    recentMonthlyBills: 'Recent Monthly Bills',
    downloadCurrentBill: 'Download Current Bill',
    updatePaymentMethod: 'Update Payment Method',
    billingPreferences: 'Billing Preferences',
    individualInvoices: 'Individual Invoices',
    exportAll: 'Export All',
    issueDate: 'Issue Date',
    viewDetails: 'View Details',
    downloadPDF: 'Download PDF',
    expires: 'Expires',
    addNewPaymentMethod: 'Add New Payment Method',
    cardNumber: 'Card Number',
    cardholderName: 'Cardholder Name',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    setAsDefaultPaymentMethod: 'Set as default payment method',
    businessVerification: 'Business Verification',
    businessVerificationDescModal: 'To enable monthly billing, we need to verify your business information. This process typically takes 2-3 business days.',
    yourBusinessName: 'Your Business Name',
    businessRegistrationNumber: 'Business Registration Number',
    vatNumberOrBusinessId: 'VAT Number or Business ID',
    businessAddress: 'Business Address',
    fullBusinessAddress: 'Full business address',
    submitForReview: 'Submit for Review',
    date: 'Date',
    paidBills: 'Paid Bills',
    pending: 'Pending',
    billAmount: 'Bill Amount',
    currentPeriod: 'Current Period',
    last3Months: 'Last 3 Months',
    last6Months: 'Last 6 Months',
    allTime: 'All Time',
    totalSpent: 'Total Spent',
    orderSuccessTitle: 'Order Submitted',
    remindSuccessTitle: 'Reminder Sent',
    remindSent: 'Remind request sent. The admin will process it as soon as possible.',
    reminded: 'Reminded',
  },
  zh: {
    shipping: '发货',
    ship: '发货',
    tracking: '跟踪',
    support: '支持',
    signIn: '登录',
    register: '注册',
    signOut: '退出登录',
    settings: '设置',
    adminPanel: '管理面板',
    dashboard: '个人中心',
    language: '语言',
    professionalLogistics: '为企业量身打造的智能物流解决方案',
    connectWithLeading: '为您的包裹提供高效、可靠、无缝衔接的全球物流服务。',
    shipPackages: '发货包裹',
    createShipments: '与我们的物流合作伙伴创建运单。',
    startShipping: '开始发货',
    trackDeliveries: '跟踪配送',
    realTimeTracking: '所有包裹的实时跟踪。',
    trackNow: '立即跟踪',
    billingPayments: '账单与支付',
    manageInvoices: '管理您的发票和支付方式。',
    viewBilling: '查看账单',
    monthlyBilling: '已验证商户的月账单',
    monthlyBillingDesc: '验证您的业务信息后，享受月账单的便利。所有运输费用都整合到一张月发票中，便于管理。',
    learnMore: '了解更多',
    applyForMonthlyBilling: '申请月账单',
    whyChoose: '为什么选择KAIFA EXPRESS？',
    fastDelivery: '快速配送',
    quickReliable: '在欧洲范围内快速可靠的配送',
    realTimeTrackingTitle: '实时跟踪',
    trackPackages: '实时跟踪您的包裹',
    support247: '24/7支持',
    roundTheClock: '全天候客户支持',
    quickActions: '快捷操作',
    trackPackage: '跟踪包裹',
    createShipment: '创建运单',
    viewBillingInfo: '查看账单',
    printDocuments: '打印文档',
    track: '跟踪',
    trackYourPackage: '跟踪您的包裹',
    enterTrackingNumber: '输入跟踪号',
    trackButton: '跟踪',
    recentOrders: '最近订单',
    orderHistory: '订单历史',
    orderDetail: '订单详情',
    trackingNumber: '跟踪号',
    status: '状态',
    sender: '发件人',
    recipient: '收件人',
    packageInformation: '包裹信息',
    trackingTimeline: '跟踪时间线',
    share: '分享',
    shareTo: '分享到',
    viewLogistics: '查看物流',
    pendingPickup: '待取件',
    inTransit: '运输中',
    outForDelivery: '包裹正在派送给收件人。',
    delivered: '已送达',
    attemptFailed: '派送失败',
    exception: '异常',
    cancelled: '已取消',
    packageType: '类型',
    weight: '重量 (kg)',
    length: '长度 (cm)',
    width: '宽度 (cm)',
    height: '高度 (cm)',
    description: '描述',
    serviceType: '服务类型',
    insurance: '保险',
    needsPallet: '需要托盘',
    palletSize: '托盘尺寸',
    trackingUrl: '跟踪链接',
    email: '邮箱',
    password: '密码',
    rememberMe: '记住我',
    forgotPassword: '忘记密码？',
    login: '登录',
    welcomeBack: '欢迎回来',
    loginToYourAccount: '登录您的账户',
    savedAccounts: '已保存账户',
    systemSettings: '系统设置',
    userManagement: '用户管理',
    systemLogs: '系统日志',
    orders: '订单',
    customers: '客户',
    billing: '账单',
    reports: '报告',
    save: '保存',
    cancel: '取消',
    edit: '编辑',
    delete: '删除',
    add: '添加',
    search: '搜索',
    filter: '筛选',
    export: '导出',
    import: '导入',
    download: '下载',
    upload: '上传',
    confirm: '确认',
    back: '返回',
    next: '下一页',
    close: '关闭',
    open: '打开',
    loading: '加载中...',
    error: '错误',
    success: '成功',
    warning: '警告',
    info: '信息',
    remind: '催单',
    printShare: '打印/分享',
    printPdf: '打印PDF',
    shareOrder: '分享订单',
    shareButtonMessage: '请在跟踪页面使用分享按钮获得完整功能。',
    orderDetails: '订单详情',
    packageCount: '包裹数量',
    recipientInfo: '收件人信息',
    senderInfo: '发件人信息',
    downloadPdf: '打印',
    downloadConfirm: '是否要打印订单详情？',
    selectOrderToView: '选择一个订单查看详情',
    view_all_info: '查看全部信息',
    orderNumber: '订单号',
    packageService: '包裹与服务',
    reviewOrder: '订单确认',
    addPackage: '添加包裹',
    areYouSureDeletePackage: '确定要删除这个包裹吗？此操作无法撤销。',
    deleteThisPackage: '删除此包裹',
    placeOrder: '提交订单',
    selectCountry: '选择国家',
    saveToAddressBook: '保存到地址簿',
    enterKFCode: '输入KF代码',
    searchSender: '搜索发件人',
    searchRecipient: '搜索收件人',
    document: '文件',
    fragile: '易碎品',
    electronics: '电子产品',
    serviceOptions: '服务选项',
    standardDelivery: '标准快递',
    expressDelivery: '特快',
    addInsuranceCoverage: '添加保险（+€5.99）',
    needPallet: '需要托盘？',
    pleaseSelectPalletSize: '请选择托盘尺寸',
    palletSize1: '1. 100cm × 50cm',
    palletSize2: '2. 140cm × 80cm',
    delayedPickup: '延时取货',
    delayedPickupDescription: '服务支持当日订单16:00后取件。为确保及时发货，请提前准备好包裹和面单，我们会与您联系。',
    notProvided: '未填写',
    kfCode: 'KF代码',
    pallet: '托盘',
    monthlyBillingDescription: '当月账单将发送至您的邮箱，并可以在"个人中心"查看。',
    orderSubmittedSuccessfully: '您的订单已成功提交！',
    germany: '德国',
    france: '法国',
    italy: '意大利',
    spain: '西班牙',
    netherlands: '荷兰',
    belgium: '比利时',
    austria: '奥地利',
    switzerland: '瑞士',
    fullName: '姓名',
    clear: '清除',
    phone: '电话',
    address: '地址',
    city: '城市',
    postalCode: '邮编',
    country: '国家',
    package: '包裹',
    service: '服务',
    review: '确认',
    backToHome: '← 返回首页',
    businessDays: '个工作日',
    name: '姓名',
    type: '类型',
    packageNo: '包裹编号',
    paymentMethod: '支付方式',
    no: '否',
    trackingNumberShort: '跟踪号',
    trackYourShipment: '查询您的包裹',
    enterPackageNumberPlaceholder: '请输入包裹单号',
    trackingLoading: '正在查询，请稍候...',
    viewAllInfo: '查看全部信息',
    sampleOrderNumber: '示例单号',
    pleasePasteLinkInWeChat: '请在微信中粘贴链接进行分享。',
    wechat: '微信',
    pickedUp: '已取件',
    labelCreated: '已生成面单',
    departedFromFacility: '包裹已离开发货地',
    packagePickedUpByCarrier: '包裹已被快递员取件',
    shippingLabelCreated: '已生成运单',
    frankfurtGermany: '德国法兰克福',
    berlinGermany: '德国柏林',
    backToTrack: '返回跟踪',
    shipmentHistory: '历史运单',
    filters: '筛选',
    prev: '上一页',
    showingShipments: '显示',
    of: '共',
    backToOrderHistory: '返回历史订单',
    orderPlaced: '已下单',
    orderPlacedDesc: '订单已提交，等待处理。',
    readyForPickup: '订单已准备好，等待快递员取件。',
    inTransitToDestination: '包裹正在运往目的地。',
    packageDeliveredToRecipient: '包裹已送达收件人。',
    contactCustomerService: '联系客服',
    guide: '使用指南',
    howCanWeHelp: '我们能帮您什么？',
    orderStatusAndTracking: '订单状态与跟踪咨询',
    shippingAndDelivery: '发货与配送问题',
    accountAndBilling: '账户与账单支持',
    feedbackAndSuggestions: '反馈与建议',
    userGuide: '使用指南',
    howToUse: '如何使用KAIFA EXPRESS',
    registerOrLogin: '注册或登录您的账户',
    fillSenderRecipient: '填写发件人和收件人信息',
    chooseServiceAndPackage: '选择您的运输服务和包裹信息',
    submitOrderAndPay: '提交订单并完成支付',
    trackShipment: '实时跟踪您的包裹',
    faq: '常见问题',
    faqTrackOrder: '如何跟踪我的订单？',
    faqShippingOptions: '有哪些运输选项？',
    faqContactCustomerService: '如何联系客服？',
    faqChangeAddress: '如何更改收货地址？',
    statTotalOrders: '总订单数',
    statActiveCustomers: '活跃客户',
    statInTransit: '运输中',
    statRevenue: '收入 (€)',
    statFromLastMonth: '较上月',
    topRoutes: '热门路线',
    ordersLabel: '单',
    revenueLabel: '收入',
    createOrder: '创建订单',
    addNewShipment: '添加新运单',
    addCustomer: '添加客户',
    registerNewCustomer: '注册新客户',
    viewReports: '查看报表',
    analyticsInsights: '分析与洞察',
    kaifaAdmin: 'KAIFA 管理',
    superAdmin: '超级管理员',
    admin: '管理员',
    searchPlaceholder: '搜索...',
    paymentManagement: '付款管理',
    all: '全部',
    paid: '已付',
    unpaid: '待付',
    overdue: '超期',
    customer: '客户',
    billNo: '账单号',
    amount: '金额',
    dueDate: '到期日',
    action: '操作',
    remindPayment: '催款',
    remindAreaTitle: '催单提醒',
    noReminders: '暂无催单',
    clearReminders: '清除',
    processReminders: '一键处理',
    businessVerificationRequired: '需要企业认证',
    businessVerificationDesc: '如需开通月结及其他高级功能，请先完成企业认证。',
    monthlyShippingServices: '{month}月运输服务',
    expressDeliveryServices: '{month}特快服务',
    standardDeliveryServices: '{month}标准服务',
    overnightDeliveryServices: '{month}隔夜服务',
    billingAndPayments: '账单与支付',
    verificationStatusPending: '待审核',
    verificationStatusApproved: '已通过',
    verificationStatusRejected: '已拒绝',
    addPaymentMethod: '添加支付方式',
    setAsDefault: '设为默认',
    default: '默认',
    remove: '移除',
    overview: '总览',
    invoices: '发票',
    monthlyBills: '月账单',
    paymentMethods: '支付方式',
    current: '本期',
    previous: '上期',
    due: '到期',
    view: '查看',
    details: '详情',
    shipments: '发货数',
    period: '账单周期',
    registrationDate: '注册日期',
    businessName: '企业名称',
    eligibleForMonthlyBilling: '可开通月结',
    notEligibleForMonthlyBilling: '不可开通月结',
    verification: '认证',
    verifyNow: '立即认证',
    completeVerification: '完成认证',
    monthlyBillingStatus: '月结状态',
    monthlyBillingActive: '月结已开通',
    monthlyBillingEligibleDesc: '您的企业已具备月度合并账单资格。',
    monthlyBillingNotAvailable: '暂不支持月结',
    monthlyBillingNotAvailableDesc: '请先完成企业认证以开通月结功能。',
    recentMonthlyBills: '近期月账单',
    downloadCurrentBill: '下载本期账单',
    updatePaymentMethod: '更新支付方式',
    billingPreferences: '账单偏好设置',
    individualInvoices: '单独发票',
    exportAll: '全部导出',
    issueDate: '开票日期',
    viewDetails: '查看详情',
    downloadPDF: '下载PDF',
    expires: '到期',
    addNewPaymentMethod: '添加新支付方式',
    cardNumber: '卡号',
    cardholderName: '持卡人姓名',
    expiryDate: '有效期',
    cvv: 'CVV',
    setAsDefaultPaymentMethod: '设为默认支付方式',
    businessVerification: '企业认证',
    businessVerificationDescModal: '为开通月结功能，我们需要验证您的企业信息。通常需要2-3个工作日。',
    yourBusinessName: '企业名称',
    businessRegistrationNumber: '企业注册号',
    vatNumberOrBusinessId: 'VAT号或企业ID',
    businessAddress: '企业地址',
    fullBusinessAddress: '完整企业地址',
    submitForReview: '提交审核',
    date: '日期',
    paidBills: '已付账单',
    pending: '待处理',
    billAmount: '账单金额',
    currentPeriod: '当前期',
    last3Months: '近三个月',
    last6Months: '近六个月',
    allTime: '全部',
    totalSpent: '总支出',
    orderSuccessTitle: '下单成功',
    remindSuccessTitle: '已发送催单请求，管理员会尽快处理。',
    remindSent: '催单请求已发送，管理员会尽快处理。',
    reminded: '已催单',
  }
}

export const LanguageContext = createContext<any>(null)

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [currentLanguage, setCurrentLanguage] = useState('zh')
  const [isLanguageLoaded, setIsLanguageLoaded] = useState(false)

  useEffect(() => {
    const savedLanguage = typeof window !== 'undefined' ? localStorage.getItem('kaifa-express-language') : null
    if (savedLanguage) {
      setCurrentLanguage(savedLanguage)
    } else {
      const browserLang = typeof window !== 'undefined' ? (navigator.language || navigator.languages?.[0] || 'en') : 'en'
      const langCode = browserLang.split('-')[0].toLowerCase()
      setCurrentLanguage(['en', 'zh', 'it'].includes(langCode) ? langCode : 'en')
    }
    setIsLanguageLoaded(true)
  }, [])

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('kaifa-express-language', currentLanguage)
    }
  }, [currentLanguage])

  const languages = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'zh', name: '中文', flag: '🇨🇳' },
    { code: 'it', name: 'Italiano', flag: '🇮🇹' }
  ]

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, languages, isLanguageLoaded, translations }}>
      {children}
    </LanguageContext.Provider>
  )
} 